### ISSUE TITLE
Not able to login

### ISSUE THREAD

**Issue by vijju050491** [rezken1/healthit#1]
![login](https://user-images.githubusercontent.com/38907771/39514431-bb420042-4e14-11e8-9a39-d7b712cfcdcd.png)

**Comment by rezken1** [comment]
Hello, can you give me more info? 
Do you have you database set ?

**Comment by vijju050491** [comment]
Yes. I have used 'php artisan migrate --seed' to migrate and it got migrated to my local database, even the data from all tables are stored. 
Now I'm trying to use that data to login,then I'm not able to login .

**Comment by rezken1** [comment]
Can you access the database and change the password manually? 
Use this website to encrypt your password:  https://bcrypt-generator.com/

**Comment by vijju050491** [comment]
Yes, I tried to change password manually. Even though I'm not able to login.

**Comment by vijju050491** [comment]
I'm trying to decrypt it using this link:https://bcrypt-generator.com/ .But not able to do.

**Comment by vijju050491** [comment]
Yes, Its working. Thank you.

**Comment by rezken1** [comment]
I am glad i've helped you! 
This is a school project done in a short amount of time, probably contain some bugs and messy code.

**Comment by rezken1** [comment]
I'm glad I've helped you.
This is a school project done in a short amount of time, probably contain some bugs and messy code
